# Generated by Django 5.1.2 on 2024-10-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0002_alter_item_item_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='event_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tableinrestaurant',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='waiterhasorder',
            unique_together={('order', 'waiter')},
        ),
    ]
