# Generated by Django 5.1.2 on 2024-10-15 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0004_rename_birt_date_customer_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='rest_app.sale'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='sale_type',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
