# Generated by Django 5.1.2 on 2024-10-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_app', '0017_alter_customer_id_alter_waiter_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.ManyToManyField(through='rest_app.ItemHasOrder', to='rest_app.item'),
        ),
    ]
